postgresql:
  url: "jdbc:postgresql://localhost:5432/clever_bank"
  user: "pavel"
  password: "pavel"
  maximumPoolSize: "30"
mongo:
  client: "mongodb://localhost:27017"
  db: "currency_db"
  collection: "nb_rb_currency"
scheduler:
  monthPercentage: "1.0"
  initialDelay: "10"
  period: "30"
NbRBScheduler:
  url: "https://api.nbrb.by/exrates/rates/"
  initialDelay: "6"
  period: "86400"
