postgresql:
  url: "jdbc:postgresql://localhost:5432/clever_bank"
  user: "enter your username"
  password: "enter your password"
  maximumPoolSize: "30"
scheduler:
  monthPercentage: "1.0"
  initialDelay: "10"
  period: "30"
NbRBScheduler:
  url: "https://api.nbrb.by/exrates/rates/"
  initialDelay: "6"
  period: "3600"
