###загрузить txt файл с банковскими чеками
GET http://localhost:8080/download
Accept: text/plain
Content-Type: text/plain

BankCheck.txt

###загрузить txt файл с выписками по транзакциям пользователей за период времени
GET http://localhost:8080/download
Accept: text/plain
Content-Type: text/plain

TransactionStatement.txt

###загрузить txt файл с выписками о количестве потраченных и полученных средств за период времени
GET http://localhost:8080/download
Accept: text/plain
Content-Type: text/plain

AmountStatement.txt
